war-world-name: "mappa-war"

time-scale:
  delay: 0 # in tickrates
  period: 0 # in tickrates

kill-hologram:
  order: "DESCENDING" # DESCENDING = lowest - highest
                      # ASCENDING = highest - lowest
  limit: 5 # This must be
  format-per-player: "%username% - %kill_count%" # Use MiniMessage as well
  header: "------- HEADER ------" # Use MiniMessage <color> <gradient:x:y>
  footer: "------- FOOTER ------" # Use MiniMessage <color> <gradient:x:y>

  hologram-details:
    world: "mappa-survival"
    x: 0.0 # Must be with decimals.
    y: 0.0 # Must be with decimals.
    z: 0.0 # Must be with decimals.
    offset-in-respect-to-y: 0 # OPTIONAL
                              # Using this will increment Y to y = y + n
                              # Example: if y is 2 and offset-in-respect-to-y is 2 y will be 4


database:
  host: "ip_address"
  port: "3306"
  username: "username"
  password: "password"
  database: "shardanaboards"